### PR TITLE
fix: skip checksum for papirus-folders

### PR DESCRIPTION
**Pull request by ghostx31**

### CODE REVIEW

**Comment by sgoudham** [comment]
Just leaving it here for the reference:

Closes https://github.com/catppuccin/papirus-folders/issues/14

**Review by sgoudham — APPROVED** [review]

**Comment by sudoAlphaX** [comment]
Greetings
Im still getting a failed validity check when trying to install papirus-folders-catppuccin-git using an AUR helper ([paru](https://github.com/Morganamilo/paru))

The error seems to be validating papirus-folders checksum fails

`==> Validating source files with md5sums...
    papirus-folders-catppuccin-git ... Skipped
    papirus-folders.hook ... Passed
    papirus-folders ... FAILED`

Checking the [PKGBUILD](https://aur.archlinux.org/packages/papirus-folders-catppuccin-git) in the AUR for papirus-folders-catppuccin-git, i can see that the checksum for papirus-folder is not SKIP, but instead `07398d48f6d86df3573fafc612c9c198`. I dont know if this repo links to a different AUR package or not.

But in any case, the md5 sum for papirus-folders is not wrong. I downloaded papirus-folders from the link from the link in PKGBUILD and `md5sum` the downloaded file. The result is here:

`md5sum papirus-folders
07398d48f6d86df3573fafc612c9c198  papirus-folders`

Which matches with the PKGBUILD of papirus-folders-catppuccin-git.

I dont know why it is failing.

Host details:
Arch x86_64
6.9.4-arch1-1
paru v2.0.3 - libalpm v14.0.0

**Comment by sgoudham** [comment]
How interesting... @sudoAlphaX 

Originally this PR was to skip the hash but the hash commited by our CI/CD workflow does match the upstream script, as you've confirmed in your testing.

We also don't know why it's failing :/

**Comment by sudoAlphaX** [comment]
I wonder if its a paru specific issue. Ill try using another AUR Helper (yay) and report the results.

**Pull request merged**
